version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:18.17.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: 
          name: Install Terraform
          command: |
            curl -LO "https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip"
            unzip terraform_1.5.3_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            terraform version

      - run: |
          export AWS_ACCESS_KEY_ID=AKIAVXVHRLCE437TPIXK
          export AWS_SECRET_ACCESS_KEY=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
          echo "Navigating to Terraform folder"
          cd terraform
          ls
          echo "Running terrafrom init"
          terraform init
          ls
          echo "Running terrafrom validate"
          terraform validate
          echo "Running terrafrom apply"
          terraform apply -auto-approve


workflows:
  my-workflow:
    jobs:
      - hello-job