version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:18.17.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: 
          name: Install Terraform
          command: |
            curl -LO "https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip"
            unzip terraform_1.5.3_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            terraform version

      - run: 
          name: Deploy terraform
          command: |
          pwd
          cd Terraform
          pwd
          terraform init
          terraform validate
      # - run: terraform apply


workflows:
  my-workflow:
    jobs:
      - hello-job